name: Install python and chromedriver
description: Run an npm script in a working directory
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13'
  chrome-version:
    description: 'Chrome version and driver version to install'
    required: false
    default: '146.0.7680.153'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v4
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
    - name: Install Chrome
      shell: bash
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo mkdir -p /etc/apt/sources.list.d
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get -y install google-chrome-stable=${{ inputs.chrome-version }}
    - name: Install ChromeDriver
      shell: bash
      run: |
        # Using specific ChromeDriver version for Chrome
        echo "Installing ChromeDriver version: ${{ inputs.chrome-version }}"
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ inputs.chrome-version }}/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        chmod +x chromedriver-linux64/chromedriver
        sudo mv chromedriver-linux64/chromedriver /usr/bin/google-chrome
    - name: 'Check google chrome version'
      shell: bash
      run: google-chrome --version
