name: Develop
on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

#post-merge-develop
jobs:
  dev_sanity_check:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - run: echo "Develop Sanity Check"

  main_linter_check:
    needs: dev_sanity_check
    uses: ./.github/workflows/lint.yml
    with:
      environment: develop

  dev_smoke_tests:
    needs: dev_sanity_check
    runs-on: ubuntu-latest
    environment:
      name: develop
      deployment: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - run: echo "Develop Smoke Tests"
