
name: Develop
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

#post-merge-develop
jobs:
  dev_smoke_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: echo "Develop Smoke Tests"

  dev_sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Develop Sanity Check"
