name: Develop Daily

on:
  schedule:
    - cron: '30 05 * * *'
  workflow_dispatch:

jobs:
  dev_integration_tests_api_daily:
    name: Dev - Integration Tests API (daily)
    runs-on: ubuntu-latest
    environment:
      name: develop
      deployment: false
    steps:
      - uses: actions/checkout@v5
        with:
          ref: develop
      - uses: ./.github/workflows/actions/setup-node
      - run: echo "Daily Integration Tests API (Develop)"
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: start
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: test:api
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: stop
