name: Develop
on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  dev_linter_check:
    uses: ./.github/workflows/lint.yml
    with:
      environment: develop

  dev_unit_tests:
    needs: dev_linter_check
    runs-on: ubuntu-latest
    environment:
      name: develop
      deployment: false
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/actions/setup-node
      - run: echo "Develop Unit Tests"
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: test:unit

  dev_smoke_tests:
    needs: dev_unit_tests
    runs-on: ubuntu-latest
    environment:
      name: develop
      deployment: false
    steps:
      - uses: actions/checkout@v5
        with:
          ref: develop
      - run: echo "Develop Smoke Tests"

  dev_deploy:
    needs: dev_smoke_tests
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v5
        with:
          ref: develop
      - run: echo "Develop Deploy"

  dev_sanity_check:
    needs: dev_deploy
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v5
        with:
          ref: develop
      - run: echo "Develop Sanity Check"

  dev_e2e_tests_pr:
    needs: dev_sanity_check
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/actions/setup-selenium
      - uses: ./.github/workflows/actions/setup-node
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: test:e2e:install:ci
      # - uses: nanasess/setup-chromedriver@v2
      # - run: chromedriver --version
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: start
      - run: echo "Develop E2E Tests"
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: test:e2e:ci
      - uses: ./.github/workflows/actions/run-npm-cmd
        with:
          script: stop
