
name: Hotfix PR
on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  call-guard:
    uses: ./.github/workflows/guard.yml

  test_hotfix:
    needs: call-guard
    if: needs.call-guard.outputs.IS_HOTFIX == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running PR workflow for hotfix/*"
