name: Hotfix PR
on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  call-guard:
    uses: ./.github/workflows/guard.yml
    with:
      environment: hotfix

  is_hotfix_pr:
    needs: call-guard
    if: needs.call-guard.outputs.IS_HOTFIX == 'true'
    runs-on: ubuntu-latest
    environment: hotfix
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running PR workflow for hotfix/*"

  hotfix_linter_check_pr:
    needs: is_hotfix_pr
    runs-on: ubuntu-latest
    environment: hotfix
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hotfix PR Linter Check"

  hotfix_secret_check_pr:
    needs: is_hotfix_pr
    runs-on: ubuntu-latest
    environment: hotfix
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hotfix PR Secret Check"

  hotfix_unit_tests_pr:
    needs: [hotfix_linter_check_pr, hotfix_secret_check_pr]
    runs-on: ubuntu-latest
    environment: hotfix
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hotfix PR Unit Tests"

  hotfix_integration_tests_pr:
    needs: hotfix_unit_tests_pr
    runs-on: ubuntu-latest
    environment: hotfix
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hotfix PR Integration Tests"
