name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

#post-merge-main
jobs:
  main_sanity_check:
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: ./.github/workflows/actions/setup-node
      - run: echo "Production checks running"

  main_linter_check:
    needs: main_sanity_check
    uses: ./.github/workflows/lint.yml
    with:
      environment: main

  main_unit_tests:
    needs: main_linter_check
    runs-on: ubuntu-latest
    environment:
      name: main
      deployment: false
    steps:
      - uses: actions/checkout@v4
      - run: echo "Main Unit Tests"

  main_integration_tests:
    needs: main_unit_tests
    runs-on: ubuntu-latest
    environment:
      name: main
      deployment: false
    steps:
      - uses: actions/checkout@v4
      - run: echo "Main Integration Tests"

  main_smoke_tests:
    needs: main_integration_tests
    runs-on: ubuntu-latest
    environment:
      name: main
      deployment: false
    steps:
      - uses: actions/checkout@v4
      - run: echo "Main Smoke Tests"

  main_system_tests:
    needs: main_smoke_tests
    runs-on: ubuntu-latest
    environment:
      name: main
      deployment: false
    steps:
      - uses: actions/checkout@v4
      - run: echo "Main System Tests"

  main_e2e_tests:
    needs: main_system_tests
    runs-on: ubuntu-latest
    environment:
      name: main
      deployment: false
    steps:
      - uses: actions/checkout@v4
      - run: echo "Main E2E Tests"
