
name: Release PR
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  call-guard:
    uses: ./.github/workflows/guard.yml

  test_release:
    needs: call-guard
    if: needs.call-guard.outputs.IS_RELEASE == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running PR workflow for release/*"
